version: '3'

services:
    app:
        build: ./docker/apache
        ports:
            - 8082:80
        volumes:
            - ./www:/var/www/html
        links:
            - db_lesson:postgres

    db_lesson:
        image: postgres:13 # set version to 9 if you encounter problems.
        volumes:
            - pg-data-bdd:/var/log/postgresql
            - pg-data-bdd:/var/lib/postgresql/data
            - ./intelliCar.sql:/docker-entrypoint-initdb.d/intelliCar.sql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
            - POSTGRES_DB=IntelliCar
            
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.com
            PGADMIN_DEFAULT_PASSWORD: root
            PG_DATABASE: intelliCar
            PG_USER: postgres
            PG_PASSWORD: root
        volumes:
            - ./docker/pgadmin:/root/.pgadmin
        ports:
            - 8080:80
        links:
            - db_lesson:postgres
volumes:
    pg-data-bdd: